export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAILED = "GET_MOVIE_LIST_FAILED";

export const GET_MOVIE_DETAIL_SUCCESS = "GET_MOVIE_DETAIL_SUCCESS";
export const GET_MOVIE_DETAIL_FAILED = "GET_MOVIE_DETAIL_FAILED";

export const GET_THEATER_SYSTEM_LIST_SUCCESS =
  "GET_THEATER_SYSTEM_LIST_SUCCESS";
export const GET_THEATER_SYSTEM_LIST_FAILED = "GET_THEATER_SYSTEM_LIST_FAILED";

export const GET_SCHEDULE_THEATER_SYSTEM_SUCCESS =
  "GET_SCHEDULE_THEATER_SYSTEM_SUCCESS";
export const GET_SCHEDULE_THEATER_SYSTEM_FAILED =
  "GET_SCHEDULE_THEATER_SYSTEM_FAILED";

export const GET_CINEMA_SYSTEM_INFOMATION_SUCCESS =
  "GET_CINEMA_SYSTEM_INFOMATION_SUCCESS";
export const GET_CINEMA_SYSTEM_INFOMATION_FAILED =
  "GET_CINEMA_SYSTEM_INFOMATION_FAILED";

// booking
export const GET_BOOKING_SUCCESS = "GET_BOOKING_SUCCESS";
export const CHOOSE_SEAT = "CHOOSE_SEAT";
export const GET_BOOKING_FAILED = "GET_BOOKING_FAILED";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_CLEAR_DATA = "USER_CLEAR_DATA";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_SIGNUP_REQUEST = "USER_SIGNUP_REQUEST";
export const USER_SIGNUP_SUCCESS = "USER_SIGNUP_SUCCESS";
export const USER_SIGNUP_FAILED = "USER_SIGNUP_FAILED";
export const USER_INFOMATION_USER_SUCCESS = "USER_INFOMATION_USER_SUCCESS";
export const USER_INFOMATION_USER_FAILED = "USER_INFOMATION_USER_FAILED";

export const REDIRECT_CLEAR_ERROR = "REDIRECT_CLEAR_ERROR";
